site_name: DarkWolfAttano
nav:
  - Home: 
    - About Me: index.md    
    - Active Projects: Active Groups.md
    - Previous Projects: Previous Groups.md
  - CodeExamples: 
    - Robot: ControlPanel.md
    - SelfBuilding: Building.md
  - FAQ: FAQ.md
  - Contact Me: Contact.md

theme:
  name: material
  font:
    text: Playfair Display
    code: Red Hat Mono
  logo: Assets/Logo.png
  favicon: Assets/Logo.png
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.instant.prefetch
    

 
  palette: 
    #Dark Mode
    - scheme: slate
      toggle:
        icon: material/account-cowboy-hat
        name: Dark mode
      primary: lime
      accent: pink
    #Light Mode
    - scheme: default
      toggle: 
        icon: material/account-cowboy-hat-outline
        name: Light mode
      primary: red
      accent: purple
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: _span
      pygments_lang_class: true
  - pymdownx.superfences 
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@ThatOneScripts
copyright: Â© 2024 DarkWolfAttano DarkWolfAttano. All rights reserved.
  
      
